language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
install:
  - pip install django-debug-toolbar.
  - pip install -r requirements-dev.txt
  - pip install https://github.com/django/django/archive/${DJANGO}.zip#egg=django
script: make test
env:
  - DJANGO=1.4.7
  - DJANGO=1.5.3
  - DJANGO=stable/1.6.x
matrix:
  exclude:
    - python: 3.2
      env: DJANGO=1.4.7
    - python: 3.3
      env: DJANGO=1.4.7